services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - DB_PATH=/app/data/data.db
    volumes:
      - bot_data:/app/data
      - ./data/images:/app/data/images
      - ./data/photo_cache:/app/data/photo_cache
      - ./creds.json:/app/creds.json

volumes:
  bot_data:



